image:
  file: .gitpod.Dockerfile

ports:
  # Sidecar API port
  - port: 3999
    onOpen: open-preview
  - port: 1000-65535
    onOpen: ignore

tasks:
  - init: npm install
    command: npm run dev
  - openMode: split-right
    command: stacks-node start --config=stacks-blockchain/Stacks-dev.toml
