version: '3.7'
services:
  postgres:
    image: "postgres:12.2"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stacks_core_sidecar
      POSTGRES_PORT: 5432
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    networks:
      - backend
  stacks-blockchain:
    build:
      context: ./stacks-blockchain/docker
    command: blockstack-core testnet /app/config/Stacks.toml
    restart: on-failure
    environment:
      STACKS_EVENT_OBSERVER: sidecar:3700
    ports:
      - "9000:9000"
    volumes:
      - ./stacks-blockchain/:/app/config
      - ./stacks-blockchain/.chaindata:/tmp/stacks-blockchain-data
      - mempool-data:/tmp/stacks-blockchain-mempool
    networks:
      - backend
    depends_on: 
      - sidecar
  sidecar:
    build:
      context: .
    environment:
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_DB: stacks_core_sidecar
      STACKS_SIDECAR_SOCKET_PORT: 3700
      STACKS_SIDECAR_SOCKET_HOST: 0.0.0.0
      STACKS_SIDECAR_API_PORT: 3999
      STACKS_SIDECAR_API_HOST: 0.0.0.0
      STACKS_SIDECAR_DB: memory
      STACKS_CORE_MEMPOOL_PATH: /tmp/stacks-blockchain-mempool
      NODE_ENV: development
    ports:
      - "3700:3700"
      - "80:3999"
    volumes:
      - ./stacks-blockchain/:/app/config
      - mempool-data:/tmp/stacks-blockchain-mempool
    networks:
      - backend
    depends_on: 
      - postgres

networks:
  frontend:
  backend:

volumes:
  database-data:
  mempool-data:
