version: '3.7'
services:
  stacks-blockchain:
    build:
      context: ./stacks-blockchain/docker
    command: wait-for-it.sh host.docker.internal:3700 -t 30 --strict -- stacks-node start --config=/app/config/Stacks-dev.toml
    restart: on-failure
    environment:
      STACKS_EVENT_OBSERVER: host.docker.internal:3700
      NOP_BLOCKSTACK_DEBUG: 1
    ports:
      - "20443:20443"
      - "20444:20444"
    volumes:
      - ./stacks-blockchain/:/app/config
      - ./stacks-blockchain/.chaindata:/tmp/stacks-blockchain-data
