version: '3.7'
services:
  stacks-blockchain:
    build:
      context: ./stacks-blockchain/docker
    command: blockstack-core testnet /app/config/Stacks.toml
    restart: on-failure
    environment:
      STACKS_EVENT_OBSERVER: host.docker.internal:3700
      # RUST_BACKTRACE: full
    ports:
      - "9000:9000"
    volumes:
      - ./stacks-blockchain/:/app/config
      - ./stacks-blockchain/.chaindata:/tmp/stacks-blockchain-data
      - ./stacks-blockchain/.mempool:/tmp/stacks-blockchain-mempool
