openapi: '3.0.0'
info:
  title: Stacks 2.0 Explorer
  version: '1.0.0'
paths:
  /sidecar/v1/tx:
    get:
      summary: Transaction list
      operationId: list_transactions
      responses:
        200:
          description: Returns list of most transactions
          content:
            application/json:
              schema:
                $ref: ./api/transaction/get-transactions.schema.json
              example:
                $ref: ./api/transaction/get-transactions.example.json
  /sidecar/v1/tx/{tx_id}:
    parameters:
      - name: tx_id
        in: path
        description: Hash of transaction
        required: true
        schema:
          type: string
    get:
      summary: Transaction by ID
      operationId: get_transaction_by_id
      responses:
        200:
          description: Transaction found
          content:
            application/json:
              schema:
                $ref: ./entities/transactions/transaction.schema.json
              example:
                $ref: ./entities/transactions/transaction-4-coinbase.example.json
        404:
          description: Cannot find transaction of given ID
  /contract/{contract_id}:
    parameters:
      - name: contract_id
        in: path
        description: Contract ID
        required: true
        schema:
          type: string
    get:
      summary: Contract by address
      operationId: get_contract_by_id
      responses:
        200:
          description: Contract found
        404:
          description: Contract not found
