name: gh-pages

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install client deps
        run: npm install
        working-directory: client

      - name: Generate client docs
        run: npm run generate:docs
        working-directory: client

      - name: Install deps
        run: npm install
        working-directory: docs

      - name: Generate and deploy gh-pages
        run: npm run deploy:docs
        working-directory: docs
