name: gh-pages
env:
  COMMIT_USER: Hiro DevOps
  COMMIT_EMAIL: 45208873+blockstack-devops@users.noreply.github.com

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install client deps
        run: npm install
        working-directory: client

      - name: Generate client docs
        run: npm run generate:docs
        working-directory: client

      - name: Install deps
        run: npm install
        working-directory: docs

      - name: Generate and deploy gh-pages
        run: |
          git config --global user.email "${COMMIT_EMAIL}"
          git config --global user.name "${COMMIT_USER}"
          npm run deploy:docs
        working-directory: docs
