name: Linting

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1

      - name: Install ESLint
        run: npm i eslint

      - name: Lint ESLint
        run: npm run lint:eslint

      - name: Install Prettier
        run: npm i prettier

      - name: Lint Prettier
        run: npm run lint:prettier
        env:
          CI: true
