name: Linting

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install deps
        run: npm install

      - name: Use Node.js
        uses: actions/setup-node@v1

      - name: Lint JSON
        run: npm run lint:json

      - name: Lint YAML
        run: npm run lint:yaml

      - name: Lint ESLint
        run: npm run lint:eslint

      - name: Lint Prettier
        run: npm run lint:prettier
        env:
          CI: true
