name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'

      - name: Install deps
        run: npm install

      - name: Setup integration environment
        run: npm run devenv:deploy -- -d

      - name: Run tests
        run: npm run test

      - name: Teardown integration environment
        run: npm run devenv:stop

      - name: Test docker build
        run: docker-compose build

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
